version: "3.5"

volumes:
  redis-cake:
  mariadb-data-cake:
  postgres-data-cake:
    driver: local

networks:
  network-cake:

services:
  memcached-cake:
    networks:
      - network-cake
    container_name: memcached-cake
    image: "memcached:alpine"
    env_file:
      - "./config/memcached.env"
    expose:
      - "11212"
    ports:
      - "11212:11212"
    command:
      - "-p 11212"
    restart: always

  redis-cake:
    networks:
      - network-cake
    container_name: redis-cake
    image: "redis:alpine"
    volumes:
      - redis-cake
    env_file:
      - "./config/redis.env"
    expose:
      - "16379"
    ports:
      - "16379:16379"
    command: --port 16379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always

  cli-cake:
    networks:
      - network-cake
    container_name: cli-cake
    image: cli
    build: config/docker/cli
    depends_on:
      - memcached-cake
      - redis-cake
      - mariadb-cake
      - mailhog-cake
    working_dir: "/application/http"
    volumes:
      - "./application/http:/application/http:consistent"
      - "./config/docker/cli/php/conf.d/50-setting.ini:/etc/php7/conf.d/50-setting.ini:cached"
      - "./config/docker/cli/php/conf.d/50-setting.ini:/etc/php7.2/conf.d/50-setting.ini:cached"
      - "./logs/php:/var/log/php:delegated"
    env_file:
      - "./config/mariadb.env"
      - "./config/memcached.env"
      - "./config/redis.env"
    command: tail -f /dev/null

  php-fpm-cake:
    networks:
      - network-cake
    container_name: php-fpm-cake
    build: config/docker/php-fpm
    depends_on:
      - memcached-cake
      - redis-cake
      - mariadb-cake
      - mailhog-cake
    working_dir: "/application/http"
    volumes:
      - "./application/http:/application/http:consistent"
      - "./config/docker/php-fpm/conf.d/50-setting.ini:/etc/php7/conf.d/50-setting.ini:cached"
      - "./config/docker/php-fpm/conf.d/50-setting.ini:/etc/php7.2/conf.d/50-setting.ini:cached"
      - "./config/docker/php-fpm/php-fpm.d/php-fpm.conf:/etc/php7/php-fpm.conf:cached"
      - "./config/docker/php-fpm/php-fpm.d/php-fpm.conf:/etc/php7.2/php-fpm.conf:cached"
      - "./logs/php-fpm:/var/log/php-fpm:delegated"
    env_file:
      - "./config/mariadb.env"
      - "./config/memcached.env"
      - "./config/redis.env"
    ports:
      - "9000:9000"
    expose:
      - "9000"

  nginx-cake:
    networks:
      - network-cake
    container_name: nginx-cake
    image: nginx
    links:
      - php-fpm-cake
      - mailhog-cake
    ports:
      - "3000:80"
      - "3001:443"
      - "8080:8080"
      - "8081:8081"
    expose:
      - "3000"
      - "3001"
      - "8080"
      - "8081"
    working_dir: "/application/http"
    volumes:
      - "./application/http:/application/http:consistent"
      - "./config/docker/nginx/conf.d:/etc/nginx/conf.d:cached"
      - "./config/docker/nginx/includes:/etc/nginx/includes:cached"
      - "./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached"
      - "./config/docker/nginx/sites-enabled:/etc/nginx/sites-enabled:cached"
      - "./config/ssl/certs:/etc/ssl/certs:cached"
      - "./config/ssl/private:/etc/ssl/private:cached"
      - "./logs/nginx:/var/log/nginx:delegated"

  mariadb-cake:
    networks:
      - network-cake
    container_name: mariadb-cake
    image: "mariadb:10.3"
    ports:
      - "3003:3306"
    working_dir: "/application/data/mariadb"
    volumes:
      - mariadb-data-cake:/var/lib/mysql
    env_file:
      - "./config/mariadb.env"
    command: "mysqld --log-bin-trust-function-creators=1 --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_bin"

  postgres:
    networks:
      - network-cake
    container_name: postgres-cake
    image: postgres
    working_dir: "/application/data/postgres"
    volumes:
      - postgres-data-cake:/var/lib/postgresql/data
    ports:
      - 5433:5433
    environment:
      - DEBUG=false
      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=

  mailhog-cake:
    networks:
      - network-cake
    container_name: mailhog-cake
    image: "mailhog/mailhog:latest"
    expose:
      - "1026"
      - "8026"
    ports:
      - "1026:1026"
      - "8026:8026"
    environment:
      - "port=1026"
      - "HOST_PORT_MAILHOG=1026"
      - "MH_SMTP_BIND_ADDR=0.0.0.0:1026"
      - "MH_UI_BIND_ADDR=0.0.0.0:8026"
      - "MH_API_BIND_ADDR=0.0.0.0:8026"
